// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2i2KHmJBuUFC0xhp85QD4ep5E77ypMNA',
    appId: '1:59763426729:android:c25aa6291b4b3a275db0b8',
    messagingSenderId: '59763426729',
    projectId: 'rehist-56806',
    databaseURL: 'https://rehist-56806-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rehist-56806.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABClLEcdnPwNOXnZ-cHCHHJHStL2Y29wk',
    appId: '1:59763426729:ios:8ca072701a399d985db0b8',
    messagingSenderId: '59763426729',
    projectId: 'rehist-56806',
    databaseURL: 'https://rehist-56806-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rehist-56806.appspot.com',
    iosClientId: '59763426729-2filfm11a7kbvhksrl35p5qi4qpm85vt.apps.googleusercontent.com',
    iosBundleId: 'com.example.rehist',
  );
}
